<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>{{ $notifTitle }}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { background-color: #f1f5f9; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1e293b; -webkit-font-smoothing: antialiased; }
    a { color: inherit; text-decoration: none; }
    img { display: block; border: 0; }

    .wrapper  { max-width: 560px; margin: 32px auto; padding: 0 16px 48px; }
    .card     { background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,.08), 0 4px 16px rgba(0,0,0,.06); }

    /* Header */
    .header        { background: #1e293b; padding: 24px 32px; display: flex; align-items: center; }
    .header-logo   { width: 48px; height: 48px; border-radius: 12px; overflow: hidden; background: #fff; flex-shrink: 0; display: flex; align-items: center; justify-content: center; margin-right: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
    .header-logo img { width: 32px; height: 32px; object-fit: contain; }
    .header-title  { color: #f8fafc; font-size: 16px; font-weight: 800; letter-spacing: -0.01em; line-height: 1.2; }
    .header-text   { display: block; }
    .header-sub    { color: #94a3b8; font-size: 11px; margin-top: 3px; font-weight: 500; text-transform: uppercase; letter-spacing: 0.05em; }

    /* Banner */
    .banner          { padding: 11px 28px; font-size: 12px; font-weight: 600; letter-spacing: 0.2px; display: flex; align-items: center; gap: 8px; background: #eff6ff; color: #1d4ed8; border-bottom: 1px solid #bfdbfe; }
    .banner-dot      { width: 7px; height: 7px; border-radius: 50%; flex-shrink: 0; background: #3b82f6; }

    /* Body */
    .body      { padding: 28px 28px 24px; }
    .meta-info { font-size: 13px; color: #64748b; margin-bottom: 24px; line-height: 1.5; }
    .meta-label { font-size: 10px; font-weight: 800; text-transform: uppercase; color: #94a3b8; margin-bottom: 4px; display: block; }
    .meta-value { font-weight: 600; color: #334155; }
    
    .section-title { font-size: 14px; font-weight: 700; color: #0f172a; margin-bottom: 8px; }
    .message-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; font-size: 13px; color: #334155; line-height: 1.65; white-space: pre-wrap; }

    /* Divider */
    .divider { border: none; border-top: 1px solid #f1f5f9; margin: 0; }

    /* Footer */
    .footer   { padding: 18px 28px; text-align: center; }
    .footer p { font-size: 11px; color: #94a3b8; line-height: 1.6; }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="card">

      {{-- Header --}}
      <div class="header">
        <div class="header-logo">
          <img src="{{ $appUrl }}/favicon.png" alt="Logo" />
        </div>
        <div class="header-text">
          <div class="header-title">{{ $appName }} Support</div>
          <div class="header-sub">Official Report Submission</div>
        </div>
      </div>

      <div class="banner">
        <span class="banner-dot"></span>
        Incoming Support Request
      </div>

      {{-- Body --}}
      <div class="body">
        <div class="meta-info">
          <div>
            <span class="meta-label">Submitted By</span>
            <span class="meta-value">{{ $senderName }} ({{ $senderEmail }})</span>
          </div>
          <div style="margin-top: 12px;">
            <span class="meta-label">Date Submitted</span>
            <span class="meta-value">{{ now()->toDayDateTimeString() }}</span>
          </div>
        </div>

        <div class="section-title">Issue Details: {{ $notifTitle }}</div>
        <div class="message-box">
          {!! nl2br(e($notifMessage)) !!}
        </div>

        @if(count($attachmentPaths) > 0)
          <div style="margin-top: 28px; padding: 16px; background: #f0f9ff; border: 1px solid #bae6fd; border-radius: 12px; display: flex; align-items: center; gap: 12px;">
            <div style="font-size: 20px;">📎</div>
            <div>
              <p style="font-size: 13px; color: #0369a1; font-weight: 700;">
                {{ count($attachmentPaths) }} Files Attached
              </p>
              <p style="font-size: 11px; color: #0ea5e9; margin-top: 1px; font-weight: 500;">
                Reference images are available at the bottom of this email.
              </p>
            </div>
          </div>
        @endif
      </div>

      <hr class="divider" />

      {{-- Footer --}}
      <div class="footer">
        <p>
          This is an automated report generated by the {{ $appName }} Help Center.<br />
          &copy; {{ date('Y') }} {{ $appName }}. All rights reserved.
        </p>
      </div>

    </div>
  </div>
</body>
</html>
