export const EVENT_LABELS: Record<string, string> = {
  "auth.login": "Logged in",
  "auth.login_failed": "Failed login attempt",
  "auth.logout": "Logged out",
  "profile.updated": "Profile updated",
  "profile.password_changed": "Password changed",
  "auth.2fa_enabled": "2FA Enabled",
  "auth.2fa_disabled": "2FA Disabled",
  "admin.2fa_reset": "2FA Administratively Reset",
  "workflow.distributed": "Document distributed",
  "workflow.sent_to_review": "Sent for review",
  "workflow.forwarded_to_vp": "Forwarded to VP",
  "workflow.forwarded_to_president": "Forwarded to President",
  "workflow.sent_to_approval": "Sent for approval",
  "workflow.sent_to_registration": "Sent for registration",
  "workflow.registered": "Document registered",
  "workflow.returned_to_draft": "Returned to draft",
  "workflow.returned_for_check": "Returned for final check",
  "workflow.rejected": "Rejected",
  "workflow.action": "Workflow action",
  "document.created": "Document created",
  "document.tags_updated": "Tags updated",
  "version.file_uploaded": "File uploaded",
  "version.file_replaced": "File replaced",
  "version.signed_file_uploaded": "Signed document uploaded",
  "version.updated": "Draft updated",
  "version.revision_created": "Revision started",
  "version.cancelled": "Version cancelled",
  "version.deleted": "Draft deleted",
  "version.previewed": "Document previewed",
  "version.downloaded": "Document downloaded",
  "message.posted": "Comment posted",
  "document_request.created": "Document request created",
  "document_request.updated": "Request updated",
  "document_request.submission.submitted": "Submission uploaded",
  "document_request.submission.reviewed": "Submission reviewed",
  "document_request.submission.accepted": "Submission accepted",
  "document_request.submission.rejected": "Submission rejected",
  "document_request.message.posted": "Request comment posted",
  "user.created": "User created",
  "user.updated": "User updated",
  "user.disabled": "User disabled",
  "user.enabled": "User re-enabled",
  "user.deleted": "User deleted",
  "office.created": "Office created",
  "office.updated": "Office updated",
  "office.disabled": "Office disabled",
  "office.restored": "Office restored",

  "announcement.created": "Announcement created",
  "announcement.archived": "Announcement archived",
  "announcement.unarchived": "Announcement restored",
  "announcement.deleted": "Announcement deleted",
};

export function friendlyEvent(event: string): string {
  if (EVENT_LABELS[event]) return EVENT_LABELS[event];
  // Fallback: convert "announcement.created" → "Announcement Created"
  return event.replace(/[._]/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}
